
# SE DESEA ACTUALIZAR LA FECHA CON EL FORMATO CORRESPONDIENTE

name0 <- as.character(FECHA,format="%b-%Y")

name1 <- as.character(FECHA,format="%m-%Y")

# ELIMINA LA NOTACION CIENTIFICA

options(scipen=999) 

# SE AJUSTA EL FORMATO DE LAS FECHAS Y SE DIVIDE LA TABLA EN DOS UNA CON PROMEDIO MOVIL ANUAL Y OTRA NORMAL

LGD_HIST$FECHA <- as.Date(LGD_HIST$FECHA)

LGD_TDC$FECHA <- as.Date(LGD_TDC$FECHA)

LGD_HIST_PM <- LGD_HIST[,-2:-6]

LGD_HIST_S <- LGD_HIST[,1:6]

# SE TRABAJA PRIMERO CON LA LGD NORMAL DEL MES PARA ACTUALIZAR Y SE BUSCA LOS CALCULOS COMO  CASTIGO NETO, RECUPERACION DE TDC Y LA LGD

LGD_TDC <- mutate(LGD_TDC, CASTIGO_NETO=CASTIGO-NETO_REC, REC_TDC=NETO_REC/CASTIGO, LGD=(1-REC_TDC))

# SE REALIZA LA UNION DEL HISTORICO Y EL MES QUE SE DESEA ACTUALIZAR, TAMBIEN SE ORDENA LA DATA POR FECHA

LGD_ACT <- rbind(LGD_HIST_S,LGD_TDC) 

LGD_ACT_A <- arrange(LGD_ACT, desc(FECHA)) 

# SE SELCECIONA LOS ULTIMOS DOCE MESES PARA PODER ENCONTRAR EL PROMDEIO MOVIL ANUAL DEL MES QUE ESTAMOS ACTUALIZANDO

LGD_ACT_12 <- LGD_ACT_A[1:12,]

# SE CALCULA IGUAL VALORES COMO EL CASTIGO PROMEDIO MOVIL ANUAL Y NETO RECUPERADO PROMEDIO MOVIL ANUAL DEL MES A ACTUALIZAR  

FECHA <- LGD_TDC[1,1]

CPM <- data.frame("CASTIGO_PM"=colMeans(LGD_ACT_12[1:12,2]))

NRPM <- data.frame("NETO_REC_PM"=colMeans(LGD_ACT_12[1:12,3]))

# SE REALIZA LA UNION DE ESTOS VALORES

LGD_HITS_PM1 <- cbind(FECHA, CPM, NRPM)

# SE CALCULA LOS VALORES ANTERIORES PERO EN PROMEDIO MOVIL ANUAL 

LGD_HITS_PM2 <- mutate(LGD_HITS_PM1, CASTIGO_NETO_PM=CASTIGO_PM-NETO_REC_PM, REC_TDC_PM=NETO_REC_PM/CASTIGO_PM, LGD_PM=(1-REC_TDC_PM))

# SE REALIZA LA UNION DE CON EL HISTORICO

LGD_ACT_PM <- rbind(LGD_HIST_PM,LGD_HITS_PM2) 

LGD_ACT_PMA <- arrange(LGD_ACT_PM, desc(FECHA)) 

LGD_ACT_PM12 <- LGD_ACT_PMA[1:12,]

# UNION DE LAS TABLAS PARA HACER EL HISTORICO Y QUE SE UTILIZE 

LGD_HIST_NEW <- left_join(LGD_ACT_A, LGD_ACT_PMA, by="FECHA")

# RESPALDO DE LOS INSUMOS UTILIZADOS

LGD_TDC1 <- select(LGD_TDC, -LGD, -REC_TDC, -CASTIGO_NETO)

# INFORMACION DONDE SE DEBE COLOCAR LA INFORMACION PARA LAS PERDIDAS ESPERADAS  

write.xlsx(LGD_HITS_PM2, "LGD_PERDIDAS.xlsx")

# INFORMACION ACTUALIZADA

write.xlsx(LGD_ACT_PM12, paste('LGD PROMEDIO ANUAL',name0,'.xlsx'))

write.xlsx(LGD_ACT_12, paste('LGD',name0,'.xlsx'))

write.xlsx(LGD_HIST_NEW, paste('HISTORICO LGD HASTA',name0,'.xlsx'))

